"""
内置工具包

提供核心工具实现。
"""

from ..errors import ErrorCode, StandardError, ToolError
from ..base import ToolStatus, ToolResult
from .exec import (
    ExecRequest,
    ExecResponse,
    ExecTool,
    NodeTarget,
    ProcessSession,
    ProcessSessionManager,
    exec_command,
    get_session_manager,
)
from .process import (
    ProcessListRequest,
    ProcessListResponse,
    ProcessLogRequest,
    ProcessLogResponse,
    ProcessPollRequest,
    ProcessPollResponse,
    ProcessSessionInfo,
    ProcessTool,
    ProcessWriteRequest,
    create_process_tool,
)
from .web_fetch import (
    ContentExtractor,
    SSRFGuard,
    WebFetchCache,
    WebFetchRequest,
    WebFetchResponse,
    WebFetchTool,
    web_fetch,
)
from .web_search import (
    BingBackend,
    CacheInfo,
    DuckDuckGoBackend,
    SearchBackend,
    SearchCache,
    WebSearchRequest,
    WebSearchResponse,
    WebSearchResult,
    WebSearchTool,
    web_search,
)
from .memory import (
    MemoryBackend,
    MemoryEntry,
    MemoryGetTool,
    MemorySearchTool,
    InMemoryBackend,
)
from .browser import (
    BrowserState,
    BrowserTool,
    BrowserSession,
    BrowserSessionManager,
    BrowserStatusRequest,
    BrowserStatusResponse,
    BrowserStartRequest,
    BrowserStopRequest,
    BrowserSnapshotRequest,
    BrowserSnapshotResponse,
    BrowserActRequest,
    BrowserClickRequest,
    BrowserTypeRequest,
    BrowserSelectRequest,
    BrowserHoverRequest,
    BrowserPressRequest,
    BrowserScrollRequest,
    BrowserNavigateRequest,
    BrowserBackRequest,
    BrowserForwardRequest,
    BrowserTabsRequest,
    BrowserTabsResponse,
    BrowserScreenshotRequest,
    BrowserScreenshotResponse,
    BrowserUploadRequest,
    BrowserDialogRequest,
    BrowserProfileRequest,
    BrowserProfileResponse,
    ElementRef,
    TabInfo,
    get_browser_session_manager,
    browser_action,
    start_browser,
    browser_snapshot,
    browser_click,
    browser_type,
    browser_navigate,
    browser_screenshot,
    stop_browser,
)
from .file_ops import (
    ReadTool,
    WriteTool,
    EditTool,
    ApplyPatchTool,
    SessionsListTool,
    SessionsHistoryTool,
)

__all__ = [
    # 错误模型
    "ErrorCode",
    "StandardError",
    "ToolError",
    "ToolStatus",
    "ToolResult",
    # Exec 工具
    "ExecTool",
    "ExecRequest",
    "ExecResponse",
    "NodeTarget",
    "ProcessSession",
    "ProcessSessionManager",
    "get_session_manager",
    "exec_command",
    # Process 工具
    "ProcessTool",
    "ProcessListRequest",
    "ProcessListResponse",
    "ProcessPollRequest",
    "ProcessPollResponse",
    "ProcessLogRequest",
    "ProcessLogResponse",
    "ProcessWriteRequest",
    "ProcessSessionInfo",
    "create_process_tool",
    # WebFetch 工具
    "WebFetchTool",
    "WebFetchRequest",
    "WebFetchResponse",
    "SSRFGuard",
    "ContentExtractor",
    "WebFetchCache",
    "web_fetch",
    # WebSearch 工具
    "WebSearchTool",
    "WebSearchRequest",
    "WebSearchResult",
    "WebSearchResponse",
    "CacheInfo",
    "SearchBackend",
    "DuckDuckGoBackend",
    "BingBackend",
    "SearchCache",
    "web_search",
    # Memory 工具
    "MemorySearchTool",
    "MemoryGetTool",
    "MemoryEntry",
    "MemoryBackend",
    "InMemoryBackend",
    # Browser 工具
    "BrowserTool",
    "BrowserState",
    "BrowserSession",
    "BrowserSessionManager",
    "BrowserStatusRequest",
    "BrowserStatusResponse",
    "BrowserStartRequest",
    "BrowserStopRequest",
    "BrowserSnapshotRequest",
    "BrowserSnapshotResponse",
    "BrowserActRequest",
    "BrowserClickRequest",
    "BrowserTypeRequest",
    "BrowserSelectRequest",
    "BrowserHoverRequest",
    "BrowserPressRequest",
    "BrowserScrollRequest",
    "BrowserNavigateRequest",
    "BrowserBackRequest",
    "BrowserForwardRequest",
    "BrowserTabsRequest",
    "BrowserTabsResponse",
    "BrowserScreenshotRequest",
    "BrowserScreenshotResponse",
    "BrowserUploadRequest",
    "BrowserDialogRequest",
    "BrowserProfileRequest",
    "BrowserProfileResponse",
    "ElementRef",
    "TabInfo",
    "get_browser_session_manager",
    "browser_action",
    "start_browser",
    "browser_snapshot",
    "browser_click",
    "browser_type",
    "browser_navigate",
    "browser_screenshot",
    "stop_browser",
    # 文件操作工具
    "ReadTool",
    "WriteTool",
    "EditTool",
    "ApplyPatchTool",
    "SessionsListTool",
    "SessionsHistoryTool",
]
